#! /bin/bash

# Seperate
#aws cloudfront create-invalidation --distribution-id E1OTF1DFWLQTWR --paths "/cf_data/*"
#aws cloudfront create-invalidation --distribution-id E1OTF1DFWLQTWR --paths "/cf_data/CelinaSafety_Samples.zip"
#aws cloudfront create-invalidation --distribution-id E1OTF1DFWLQTWR --paths "/cf_data/CelinaSafety01*"

# Do Together
 aws cloudfront create-invalidation --distribution-id E1OTF1DFWLQTWR --paths /index.html /gallery.html /publish-hashes.json
 aws cloudfront create-invalidation --distribution-id E1OTF1DFWLQTWR --paths "/assets/dan/*"

